version: '3'
services:
  mysql-parking:
    container_name: parking-service-db
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking-service
      MYSQL_USER: root
      MYSQL_PASSWORD: K150205k

    ports:
      - "3308:3306"
    volumes:
      - ./volumes/parking:/var/lib/mysql

