server:
port: 8080

spring:
application:
name: API-GATEWAY
cloud:
gateway:
routes:
- id: PARKING-SERVICE
uri: lb://PARKING-SERVICE
predicates:
- Path=/api/v1/parkings/**


eureka:
client:
register-with-eureka: true
fetch-registry: true
service-url:
defaultZone: http://localhost:8761
instance:
hostname: localhost